### ISSUE TITLE
测试发现bug 金额超过

### ISSUE THREAD

**Issue by September999999999** [pmw1014/hongbao#3]
![image](https://user-images.githubusercontent.com/32701871/109119856-3003b280-7780-11eb-8fbf-86d8cc10457e.png)
![image](https://user-images.githubusercontent.com/32701871/109119867-32660c80-7780-11eb-999c-ae712b9896cf.png)

**Comment by pmw1014** [comment]
这是因为当前的随机算法中有自动补齐数据逻辑，如果红包生产完毕后任然有剩余金额，会自动选取一个值累加并消费余额至零。
